[General]
mode = "local"
port = 3000
host = "127.0.0.1"

[AI]
default = "OpenAI"
temperature = 0.5
max_tokens = 100

[AI.OpenAI]
base_url = "https://api.openai.com"
api_key = "YOUR_API_KEY"
temperature = 0.5
max_tokens = 100

[AI.Gemini]
api_key = ""
temperature = 0.5
max_tokens = 100

[AI.Copilot]
api_key = ""
temperature = 0.5
max_tokens = 100

[Translate]
default = "DeepLX"

[Translate.DeepLX]
# proxy_endpoint = ""
# access_token = ""

[Translate.AI]
default = "OpenAI"

[Translate.LibreTranslate]
base_url = "https://libretranslate.com"
api_key = ""
type = "reserve"

# The following is for the legacy configuration
# They will be removed in the future
[Legency]
ai_type = "OpenAI"
ai_api_key = ""
openai_base_url = "https://api.openai.com"
ai_max_tokens = 100
ai_temperature = 0.5
